#to start metric server 

#kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml    -- command to install metric server.
#kubectl edit deployment of metric-server inside it edit metric-server pod
#add --kubelet-insecure-tls in arg


apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: demo-hpa
spec:
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 50  
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
