#git clone https://github.com/kubernetes/autoscaler.git
#cd autoscaler
#./hack/vpa-up.sh
# this way it will instal vpa in cluster now you can use it.
#run below command if vps admission controller pod not started due to secrets. or add extra / at gencerts.sh in line 44 before "/cn" so it will be like "//cn"
#./pkg/admission-controller/gencerts.sh

apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: demo-vpa
spec:
  updatePolicy:
    updateMode: "Off"
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx